In [81]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("rjmanoj/credit-card-customer-churn-prediction")

print("Path to dataset files:", path)

Path to dataset files: /Users/kpvarma/.cache/kagglehub/datasets/rjmanoj/credit-card-customer-churn-prediction/versions/1

In [82]:
import pandas as pd
df=pd.read_csv('Churn_Modelling.csv')

In [83]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [84]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='str')

In [85]:
df.shape

(10000, 14)

In [86]:
df.duplicated().sum()

np.int64(0)

In [87]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [88]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [89]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [90]:
df.shape

(10000, 14)

In [91]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='str')

In [92]:
df=df.drop(columns=['RowNumber', 'CustomerId', 'Surname'])

In [93]:
df = pd.get_dummies(df, columns=['Geography', 'Gender'], drop_first=True, dtype=int)

In [94]:
X=df.drop(columns=['Exited'])
y=df['Exited']
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [95]:
X

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,0,0,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,0,0,0

In [96]:
x_train.shape

(8000, 11)

In [97]:
y_train.shape

(8000,)

In [98]:
x_test.shape

(2000, 11)

In [99]:
y_test.shape

(2000,)

In [100]:
from sklearn.preprocessing import StandardScaler
std=StandardScaler()
X_train_scaled=std.fit_transform(x_train)

In [101]:
X_test_scaled=std.fit_transform(x_test)

In [102]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [103]:
model=Sequential()
model.add(Dense(11,activation='relu',input_dim=11))
model.add(Dense(11,activation='relu',input_dim=11))
model.add(Dense(1,activation='sigmoid'))

/Users/kpvarma/PycharmProjects/Deep_Daily/.venv/lib/python3.13/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [104]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_5 (Dense)                 │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 276 (1.08 KB)

 Trainable params: 276 (1.08 KB)

 Non-trainable params: 0 (0.00 B)

In [105]:
model.compile(loss='binary_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [106]:
model.fit(X_train_scaled,y_train,epochs=100,validation_split=0.2)

Epoch 1/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 764us/step - accuracy: 0.7520 - loss: 0.5780 - val_accuracy: 0.7975 - val_loss: 0.5095
Epoch 2/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.7970 - loss: 0.4830 - val_accuracy: 0.7975 - val_loss: 0.4686
Epoch 3/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.7989 - loss: 0.4509 - val_accuracy: 0.7975 - val_loss: 0.4481
Epoch 4/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 491us/step - accuracy: 0.8048 - loss: 0.4349 - val_accuracy: 0.8019 - val_loss: 0.4375
Epoch 5/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.8125 - loss: 0.4262 - val_accuracy: 0.8062 - val_loss: 0.4308
Epoch 6/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - accuracy: 0.8194 - loss: 0.4194 - val_accuracy: 0.8131 - val_loss: 0.4231
Epoch 7/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 418us/step - accuracy: 0.8230 - loss: 0.4129 - val_accuracy: 0.8188 - val_loss: 0.4147
Epoch 8/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - accuracy: 0.8289 - loss: 0.4050 - val_accuracy: 0.8288 - val_loss: 0.4058
Epoch 9/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 413us/step - accuracy: 0.8363 - loss: 0.3962 - val_accuracy: 0.8313 - val_loss: 0.3975
Epoch 10/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 414us/step - accuracy: 0.8422 - loss: 0.3874 - val_accuracy: 0.8356 - val_loss: 0.3874
Epoch 11/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 414us/step - accuracy: 0.8458 - loss: 0.3788 - val_accuracy: 0.8381 - val_loss: 0.3798
Epoch 12/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 413us/step - accuracy: 0.8505 - loss: 0.3706 - val_accuracy: 0.8456 - val_loss: 0.3733
Epoch 13/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 423us/step - accuracy: 0.8530 - loss: 0.3640 - val_accuracy: 0.8444 - val_loss: 0.3684
Epoch 14/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.8550 - loss: 0.3582 - val_accuracy: 0.8494 - val_loss: 0.3618
Epoch 15/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 440us/step - accuracy: 0.8575 - loss: 0.3541 - val_accuracy: 0.8456 - val_loss: 0.3637
Epoch 16/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 497us/step - accuracy: 0.8564 - loss: 0.3510 - val_accuracy: 0.8500 - val_loss: 0.3569
Epoch 17/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 474us/step - accuracy: 0.8595 - loss: 0.3482 - val_accuracy: 0.8481 - val_loss: 0.3596
Epoch 18/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 498us/step - accuracy: 0.8597 - loss: 0.3465 - val_accuracy: 0.8494 - val_loss: 0.3534
Epoch 19/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 475us/step - accuracy: 0.8603 - loss: 0.3448 - val_accuracy: 0.8512 - val_loss: 0.3517
Epoch 20/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 521us/step - accuracy: 0.8606 - loss: 0.3434 - val_accuracy: 0.8494 - val_loss: 0.3535
Epoch 21/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 514us/step - accuracy: 0.8603 - loss: 0.3422 - val_accuracy: 0.8494 - val_loss: 0.3528
Epoch 22/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 505us/step - accuracy: 0.8627 - loss: 0.3411 - val_accuracy: 0.8512 - val_loss: 0.3507
Epoch 23/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 603us/step - accuracy: 0.8636 - loss: 0.3396 - val_accuracy: 0.8512 - val_loss: 0.3491
Epoch 24/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 548us/step - accuracy: 0.8627 - loss: 0.3390 - val_accuracy: 0.8519 - val_loss: 0.3481
Epoch 25/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 532us/step - accuracy: 0.8617 - loss: 0.3383 - val_accuracy: 0.8494 - val_loss: 0.3510
Epoch 26/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 477us/step - accuracy: 0.8620 - loss: 0.3373 - val_accuracy: 0.8512 - val_loss: 0.3488
Epoch 27/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 477us/step - accuracy: 0.8622 - loss: 0.3374 - val_accuracy: 0.8525 - val_loss: 0.3491
Epoch 28/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 491us/step - accuracy: 0.8616 - loss: 0.3363 - val_accuracy: 0.8531 - val_loss: 0.3464
Epoch 29/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 483us/step - accuracy: 0.8630 - loss: 0.3360 - val_accuracy: 0.8531 - val_loss: 0.3464
Epoch 30/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 471us/step - accuracy: 0.8631 - loss: 0.3349 - val_accuracy: 0.8506 - val_loss: 0.3487
Epoch 31/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 470us/step - accuracy: 0.8645 - loss: 0.3346 - val_accuracy: 0.8506 - val_loss: 0.3477
Epoch 32/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 462us/step - accuracy: 0.8636 - loss: 0.3341 - val_accuracy: 0.8494 - val_loss: 0.3482
Epoch 33/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 509us/step - accuracy: 0.8645 - loss: 0.3335 - val_accuracy: 0.8525 - val_loss: 0.3467
Epoch 34/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 473us/step - accuracy: 0.8645 - loss: 0.3333 - val_accuracy: 0.8512 - val_loss: 0.3474
Epoch 35/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 451us/step - accuracy: 0.8644 - loss: 0.3331 - val_accuracy: 0.8506 - val_loss: 0.3488
Epoch 36/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 463us/step - accuracy: 0.8637 - loss: 0.3325 - val_accuracy: 0.8531 - val_loss: 0.3457
Epoch 37/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 446us/step - accuracy: 0.8636 - loss: 0.3318 - val_accuracy: 0.8494 - val_loss: 0.3457
Epoch 38/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 441us/step - accuracy: 0.8655 - loss: 0.3318 - val_accuracy: 0.8500 - val_loss: 0.3480
Epoch 39/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 455us/step - accuracy: 0.8634 - loss: 0.3315 - val_accuracy: 0.8512 - val_loss: 0.3475
Epoch 40/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 658us/step - accuracy: 0.8656 - loss: 0.3308 - val_accuracy: 0.8537 - val_loss: 0.3487
Epoch 41/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 447us/step - accuracy: 0.8664 - loss: 0.3308 - val_accuracy: 0.8512 - val_loss: 0.3451
Epoch 42/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 440us/step - accuracy: 0.8653 - loss: 0.3303 - val_accuracy: 0.8487 - val_loss: 0.3487
Epoch 43/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 491us/step - accuracy: 0.8650 - loss: 0.3306 - val_accuracy: 0.8512 - val_loss: 0.3463
Epoch 44/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 447us/step - accuracy: 0.8642 - loss: 0.3304 - val_accuracy: 0.8506 - val_loss: 0.3458
Epoch 45/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.8664 - loss: 0.3295 - val_accuracy: 0.8506 - val_loss: 0.3466
Epoch 46/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 440us/step - accuracy: 0.8664 - loss: 0.3297 - val_accuracy: 0.8487 - val_loss: 0.3458
Epoch 47/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 454us/step - accuracy: 0.8662 - loss: 0.3294 - val_accuracy: 0.8519 - val_loss: 0.3452
Epoch 48/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.8658 - loss: 0.3288 - val_accuracy: 0.8544 - val_loss: 0.3477
Epoch 49/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.8656 - loss: 0.3289 - val_accuracy: 0.8494 - val_loss: 0.3461
Epoch 50/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.8658 - loss: 0.3289 - val_accuracy: 0.8500 - val_loss: 0.3457
Epoch 51/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.8650 - loss: 0.3281 - val_accuracy: 0.8506 - val_loss: 0.3462
Epoch 52/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 443us/step - accuracy: 0.8655 - loss: 0.3277 - val_accuracy: 0.8506 - val_loss: 0.3474
Epoch 53/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 458us/step - accuracy: 0.8664 - loss: 0.3279 - val_accuracy: 0.8494 - val_loss: 0.3483
Epoch 54/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 488us/step - accuracy: 0.8653 - loss: 0.3285 - val_accuracy: 0.8500 - val_loss: 0.3464
Epoch 55/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 426us/step - accuracy: 0.8658 - loss: 0.3280 - val_accuracy: 0.8475 - val_loss: 0.3463
Epoch 56/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 424us/step - accuracy: 0.8653 - loss: 0.3272 - val_accuracy: 0.8525 - val_loss: 0.3494
Epoch 57/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.8664 - loss: 0.3274 - val_accuracy: 0.8500 - val_loss: 0.3448
Epoch 58/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 453us/step - accuracy: 0.8669 - loss: 0.3270 - val_accuracy: 0.8512 - val_loss: 0.3456
Epoch 59/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 459us/step - accuracy: 0.8655 - loss: 0.3269 - val_accuracy: 0.8494 - val_loss: 0.3478
Epoch 60/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 437us/step - accuracy: 0.8656 - loss: 0.3269 - val_accuracy: 0.8506 - val_loss: 0.3477
Epoch 61/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 441us/step - accuracy: 0.8661 - loss: 0.3267 - val_accuracy: 0.8494 - val_loss: 0.3455
Epoch 62/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 511us/step - accuracy: 0.8659 - loss: 0.3264 - val_accuracy: 0.8469 - val_loss: 0.3474
Epoch 63/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.8659 - loss: 0.3268 - val_accuracy: 0.8506 - val_loss: 0.3471
Epoch 64/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 472us/step - accuracy: 0.8667 - loss: 0.3262 - val_accuracy: 0.8487 - val_loss: 0.3459
Epoch 65/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.8666 - loss: 0.3265 - val_accuracy: 0.8500 - val_loss: 0.3462
Epoch 66/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.8661 - loss: 0.3258 - val_accuracy: 0.8525 - val_loss: 0.3467
Epoch 67/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.8655 - loss: 0.3267 - val_accuracy: 0.8487 - val_loss: 0.3471
Epoch 68/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - accuracy: 0.8662 - loss: 0.3250 - val_accuracy: 0.8487 - val_loss: 0.3464
Epoch 69/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 423us/step - accuracy: 0.8658 - loss: 0.3259 - val_accuracy: 0.8475 - val_loss: 0.3472
Epoch 70/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - accuracy: 0.8666 - loss: 0.3253 - val_accuracy: 0.8481 - val_loss: 0.3471
Epoch 71/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - accuracy: 0.8662 - loss: 0.3247 - val_accuracy: 0.8512 - val_loss: 0.3516
Epoch 72/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.8672 - loss: 0.3249 - val_accuracy: 0.8481 - val_loss: 0.3495
Epoch 73/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 420us/step - accuracy: 0.8647 - loss: 0.3247 - val_accuracy: 0.8487 - val_loss: 0.3485
Epoch 74/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 421us/step - accuracy: 0.8675 - loss: 0.3243 - val_accuracy: 0.8487 - val_loss: 0.3492
Epoch 75/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 449us/step - accuracy: 0.8655 - loss: 0.3244 - val_accuracy: 0.8487 - val_loss: 0.3481
Epoch 76/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 435us/step - accuracy: 0.8653 - loss: 0.3244 - val_accuracy: 0.8475 - val_loss: 0.3484
Epoch 77/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 426us/step - accuracy: 0.8652 - loss: 0.3253 - val_accuracy: 0.8481 - val_loss: 0.3482
Epoch 78/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 424us/step - accuracy: 0.8647 - loss: 0.3244 - val_accuracy: 0.8481 - val_loss: 0.3492
Epoch 79/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.8677 - loss: 0.3239 - val_accuracy: 0.8487 - val_loss: 0.3475
Epoch 80/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 426us/step - accuracy: 0.8669 - loss: 0.3243 - val_accuracy: 0.8481 - val_loss: 0.3488
Epoch 81/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - accuracy: 0.8672 - loss: 0.3241 - val_accuracy: 0.8469 - val_loss: 0.3486
Epoch 82/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.8673 - loss: 0.3234 - val_accuracy: 0.8500 - val_loss: 0.3495
Epoch 83/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - accuracy: 0.8678 - loss: 0.3234 - val_accuracy: 0.8506 - val_loss: 0.3507
Epoch 84/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - accuracy: 0.8681 - loss: 0.3236 - val_accuracy: 0.8469 - val_loss: 0.3481
Epoch 85/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.8670 - loss: 0.3236 - val_accuracy: 0.8494 - val_loss: 0.3478
Epoch 86/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.8669 - loss: 0.3228 - val_accuracy: 0.8506 - val_loss: 0.3503
Epoch 87/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 743us/step - accuracy: 0.8662 - loss: 0.3230 - val_accuracy: 0.8487 - val_loss: 0.3492
Epoch 88/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 484us/step - accuracy: 0.8666 - loss: 0.3230 - val_accuracy: 0.8481 - val_loss: 0.3496
Epoch 89/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.8677 - loss: 0.3227 - val_accuracy: 0.8475 - val_loss: 0.3488
Epoch 90/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 420us/step - accuracy: 0.8669 - loss: 0.3223 - val_accuracy: 0.8487 - val_loss: 0.3505
Epoch 91/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 426us/step - accuracy: 0.8672 - loss: 0.3220 - val_accuracy: 0.8475 - val_loss: 0.3486
Epoch 92/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 446us/step - accuracy: 0.8669 - loss: 0.3228 - val_accuracy: 0.8500 - val_loss: 0.3514
Epoch 93/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 424us/step - accuracy: 0.8641 - loss: 0.3228 - val_accuracy: 0.8475 - val_loss: 0.3483
Epoch 94/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - accuracy: 0.8659 - loss: 0.3220 - val_accuracy: 0.8487 - val_loss: 0.3489
Epoch 95/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 447us/step - accuracy: 0.8672 - loss: 0.3215 - val_accuracy: 0.8475 - val_loss: 0.3484
Epoch 96/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - accuracy: 0.8686 - loss: 0.3221 - val_accuracy: 0.8494 - val_loss: 0.3506
Epoch 97/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 422us/step - accuracy: 0.8658 - loss: 0.3216 - val_accuracy: 0.8500 - val_loss: 0.3491
Epoch 98/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 421us/step - accuracy: 0.8677 - loss: 0.3216 - val_accuracy: 0.8506 - val_loss: 0.3486
Epoch 99/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 420us/step - accuracy: 0.8677 - loss: 0.3214 - val_accuracy: 0.8487 - val_loss: 0.3487
Epoch 100/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - accuracy: 0.8677 - loss: 0.3214 - val_accuracy: 0.8500 - val_loss: 0.3479

In [107]:
model.layers[0].get_weights()

[array([[ 0.15103681, -0.400071  , -0.31985232, -0.1054081 ,  0.06494483,
          0.20845826,  0.21337374, -0.09089015,  0.07701308,  0.05239005,
         -0.06030042],
        [-0.30995882, -0.24262816,  0.4806148 ,  0.53987384, -0.18055442,
         -0.58975065,  0.56089336, -0.40202355, -0.14394918,  0.28056872,
          1.4776031 ],
        [ 0.2005023 ,  0.67030454,  0.3079754 ,  0.23264696,  0.13738786,
         -0.13855906,  0.09177975,  0.24464978, -0.03783168,  0.04558248,
          0.08081837],
        [-0.23149887, -0.21398114,  0.06883018, -0.70956904, -0.65393186,
         -0.56391513, -0.20556529,  0.6183454 ,  0.54053694, -0.75688934,
          0.05580436],
        [ 1.6061914 , -0.23235458,  0.05564423,  0.08268432,  0.02060047,
         -0.05157588,  0.12564167, -0.4490953 , -0.14982922, -1.3907024 ,
          0.43545642],
        [ 0.11372401, -0.03843769,  0.32614288,  0.44777852, -0.38868675,
          0.42560953, -0.182513  ,  0.46425018,  0.36939132, -0.04524239,
          0.05182398],
        [-0.69516236,  0.50467974, -0.26611534,  0.39566383, -0.69483525,
         -0.13388067,  0.7530309 ,  0.09986573,  0.38355654, -0.75176233,
          0.11400226],
        [ 0.04743774, -0.42970526, -0.26021743, -0.09775413, -0.10618577,
         -0.09165853,  0.19153629,  0.12069835,  0.356515  ,  0.02385646,
         -0.04336997],
        [ 0.11919644, -0.07715502, -0.01622414,  0.46094078,  0.2856879 ,
         -0.23717935, -0.15694419, -0.7321098 ,  0.07514215,  0.44240215,
          0.08229649],
        [ 0.03825474,  0.3074809 , -0.41048506,  0.21552211, -0.12637301,
          0.0660006 ,  0.296718  ,  0.4900002 , -0.6075802 ,  0.04191045,
          0.11610791],
        [-0.05148735, -0.16242614,  0.65547144, -0.12805928,  0.06659827,
          0.32708025,  0.23562935, -0.10937931, -0.38443702, -0.10864688,
         -0.0528812 ]], dtype=float32),
 array([ 0.6309513 , -0.13407466, -0.14086041, -0.21061005,  0.9082949 ,
         0.93477964, -0.23986387,  0.179801  ,  0.08292224,  0.5353    ,
        -0.07842262], dtype=float32)]

In [108]:
model.layers[1].get_weights()

[array([[-1.1508479 ,  0.9444722 ,  0.19358498, -0.27888745,  0.52788496,
          0.57003707, -0.59006065,  0.6317186 , -0.16687869, -0.3242501 ,
         -0.15704672],
        [ 0.06368805,  0.02978864,  0.20026699, -0.22171234,  0.5508759 ,
          0.02552753,  0.06616076,  0.6230504 ,  0.57614267, -0.43380496,
          0.20371109],
        [-0.4267552 , -0.12297666, -0.9839409 , -0.31323266, -0.10256694,
          0.15184146,  0.33074713, -0.25961167,  0.03247995,  0.4344863 ,
          0.13406737],
        [-0.3140082 , -0.23775008, -0.1341174 , -0.550222  , -0.0315199 ,
         -0.281778  , -0.11337323, -0.6480802 ,  0.12308016, -0.11931651,
          0.5745613 ],
        [ 0.17827183, -0.35470498, -0.5731487 ,  0.19323431,  0.49489114,
          0.55219024,  0.14569275,  0.34124613,  0.23067507,  0.10292456,
          0.56713706],
        [ 0.06168544, -0.2749673 , -0.5467696 , -0.08626623,  0.09323488,
          0.2013488 ,  0.44040212,  0.19768657, -0.1456275 ,  0.6138559 ,
          0.474429  ],
        [-0.89898765, -0.10275605, -0.5813461 , -0.1323064 , -0.2950492 ,
          0.0863331 , -0.321947  ,  0.33017674,  0.6147836 ,  0.14867938,
          0.5293207 ],
        [-0.30372804,  0.23158292,  0.5357685 , -0.26636827,  0.5073837 ,
          0.21994504,  0.44309857, -0.6007959 , -0.1111186 , -0.361018  ,
          0.21361512],
        [-0.2087351 , -0.20360869, -0.05902311,  0.09223214, -0.20842247,
          0.2711554 ,  0.24031664, -0.6938955 ,  0.29209557,  0.42670217,
         -0.20597185],
        [ 0.34682584, -1.111112  , -1.2758781 , -0.21050094, -0.22082311,
         -0.0434097 ,  0.6192732 ,  0.61553323, -0.83555543, -0.5235407 ,
         -0.42298293],
        [-1.6736145 ,  0.65947104, -0.2673996 , -0.13164133, -0.620865  ,
         -0.7660046 ,  0.27955374, -0.00486694,  0.6248134 , -0.20752288,
          0.38448122]], dtype=float32),
 array([ 0.23366511, -0.46251768, -0.21226029, -0.19648264,  0.5449106 ,
         0.5766314 ,  0.23260012, -0.29115856,  0.07569128,  0.36594972,
         0.15910672], dtype=float32)]

In [109]:
y_log=model.predict(X_test_scaled)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 710us/step

In [110]:
import numpy as np
y_pred=np.where(y_log>0.5,1,0)

In [111]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8615