In [58]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("rjmanoj/credit-card-customer-churn-prediction")

print("Path to dataset files:", path)

Path to dataset files: /Users/kpvarma/.cache/kagglehub/datasets/rjmanoj/credit-card-customer-churn-prediction/versions/1

In [59]:
import pandas as pd
df=pd.read_csv('Churn_Modelling.csv')

In [60]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [61]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='str')

In [62]:
df.shape

(10000, 14)

In [63]:
df.duplicated().sum()

np.int64(0)

In [64]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [65]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [66]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [67]:
df.shape

(10000, 14)

In [69]:
df = pd.get_dummies(df, columns=['Geography', 'Gender'], drop_first=True)

# Convert True/False to 0/1
df = df.astype(int)

KeyError: "None of [Index(['Geography', 'Gender'], dtype='str')] are in the [columns]"

In [19]:
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0,1,1,1,101348,1,0,0,0
1,608,41,1,83807,1,0,1,112542,0,0,1,0
2,502,42,8,159660,3,1,0,113931,1,0,0,0
3,699,39,1,0,2,0,0,93826,0,0,0,0
4,850,43,2,125510,1,1,1,79084,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0,2,1,0,96270,0,0,0,1
9996,516,35,10,57369,1,1,1,101699,0,0,0,1
9997,709,36,7,0,1,0,1,42085,1,0,0,0
9998,772,42,3,75075,2,1,0,92888,1,1,0,1
9999,792,28,4,130142,1,1,0,38190,0,0,0,0

In [21]:
X=df.drop(columns=['Exited'])
y=df['Exited']
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [22]:
X

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0,1,1,1,101348,0,0,0
1,608,41,1,83807,1,0,1,112542,0,1,0
2,502,42,8,159660,3,1,0,113931,0,0,0
3,699,39,1,0,2,0,0,93826,0,0,0
4,850,43,2,125510,1,1,1,79084,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0,2,1,0,96270,0,0,1
9996,516,35,10,57369,1,1,1,101699,0,0,1
9997,709,36,7,0,1,0,1,42085,0,0,0
9998,772,42,3,75075,2,1,0,92888,1,0,1
9999,792,28,4,130142,1,1,0,38190,0,0,0

In [24]:
x_train.shape

(8000, 11)

In [25]:
y_train.shape

(8000,)

In [26]:
x_test.shape

(2000, 11)

In [27]:
y_test.shape

(2000,)

In [28]:
from sklearn.preprocessing import StandardScaler
std=StandardScaler()
X_train_scaled=std.fit_transform(x_train)

In [29]:
X_test_scaled=std.fit_transform(x_test)

In [30]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [47]:
model=Sequential()
model.add(Dense(11,activation='relu',input_dim=11))
model.add(Dense(11,activation='relu',input_dim=11))
model.add(Dense(1,activation='sigmoid'))

/Users/kpvarma/PycharmProjects/Deep_Daily/.venv/lib/python3.13/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [48]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 276 (1.08 KB)

 Trainable params: 276 (1.08 KB)

 Non-trainable params: 0 (0.00 B)

In [49]:
model.compile(loss='binary_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [57]:
model.fit(X_train_scaled,y_train,epochs=100,validation_split=0.2)

TypeError: TensorFlowTrainer.fit() got an unexpected keyword argument 'validation_state'. Did you mean 'validation_data'?

In [52]:
model.layers[0].get_weights()

[array([[ 0.07605733,  0.02096625, -0.18076628,  0.01125417, -0.08889335,
          0.3528997 , -0.02468067,  0.13073552, -0.12240579, -0.5643913 ,
         -0.04451509],
        [ 0.24345759, -0.82542586,  0.4977223 , -0.72678876,  0.5040553 ,
          0.05309007, -0.27998877, -0.10376237, -0.07641778,  0.03768644,
          0.18631181],
        [-0.10535539, -0.05327007,  0.05733622, -0.02358995,  0.26637417,
          0.2635444 ,  0.00835032, -0.01920794, -0.3668831 , -0.39629444,
          0.08766074],
        [-0.79687464,  0.07156571,  0.3889978 , -0.19619125, -0.02467449,
         -0.8551543 , -0.5972359 ,  0.2402349 ,  0.05378593,  0.18348373,
         -0.24713092],
        [-0.27647603, -0.29279903, -0.04965846, -0.03006489, -0.3229057 ,
         -0.26903966, -1.2859427 , -0.8464831 , -0.12656015, -0.66270506,
          1.3365357 ],
        [-0.29164883, -0.1362382 , -0.08859266,  0.126512  ,  0.34852433,
          0.0815768 , -0.07212091,  0.12082628, -0.15900275, -0.06094337,
          0.15288201],
        [ 0.8107079 , -0.2689866 , -0.20708725, -0.20015134,  0.99847585,
         -0.16330913, -0.1145813 , -0.07522506,  0.7697384 ,  0.54259604,
          0.00848629],
        [ 0.19622277,  0.04479541, -0.32187936,  0.01803156, -0.10892276,
         -0.61958987,  0.1982609 , -0.29939014,  0.10850618,  0.12313233,
         -0.05068045],
        [-0.19446546,  0.03598385,  0.00623791,  0.11158168,  0.38682115,
         -0.6336004 ,  0.45266783,  0.1523078 , -0.24073419, -0.4611912 ,
          0.13783707],
        [ 0.22865449,  0.08241901,  0.09264451, -0.01374822,  0.12462462,
         -0.05579192,  0.19454587, -0.06882466, -0.64691347, -0.12983663,
          0.32489616],
        [ 0.44698524, -0.22293626,  0.74491   ,  0.18675588, -0.17390873,
         -0.09523181,  0.22229162, -0.34625164,  0.69361424, -0.64255184,
          0.29573533]], dtype=float32),
 array([ 0.5558907 ,  0.7975538 ,  0.38061622,  1.1647624 ,  0.17322773,
         0.5137586 ,  0.11841504, -0.11198077,  0.26409838, -0.13510501,
        -0.13376704], dtype=float32)]

In [53]:
model.layers[1].get_weights()

[array([[-0.00150908,  0.04696058,  0.5434312 , -0.16806066, -0.13813528,
          0.09854612, -0.57291913,  0.40173092, -0.3044948 , -0.05738384,
          0.43579364],
        [-0.1222341 , -0.826568  , -0.11515561, -0.00295007,  0.10321291,
          0.09774671, -0.12135606, -0.03045338, -0.17041078, -0.6554494 ,
          0.36481822],
        [ 0.36962128, -0.42789006, -0.15705049, -0.15325564,  0.49213552,
          0.25145105, -0.3263663 ,  0.07872563,  0.43488353,  0.24055636,
         -0.05764645],
        [ 0.5740201 ,  0.1416416 , -0.1213751 , -0.8970866 ,  0.34880164,
         -0.02959427, -0.22023565,  0.74549675,  0.06623331, -0.97437334,
          0.17345472],
        [ 0.19703649,  0.37882173,  0.5847609 , -0.01873758,  0.20765725,
          0.16403557, -0.11028747, -0.19003424,  0.07777077, -0.48770067,
          0.6090543 ],
        [ 0.02357246,  0.32372254, -0.4976569 ,  0.28335437,  0.33885145,
         -0.15429288, -1.2029479 ,  0.15145712, -1.046887  ,  0.0605332 ,
          0.18234608],
        [-0.5303702 ,  0.93282366,  0.06199949,  0.29274222,  0.22691754,
         -0.18545482, -1.1162003 ,  0.33055732, -0.42824104,  0.78851116,
         -0.73572224],
        [-0.3141201 ,  0.35844955,  0.5117838 ,  0.31884956,  0.28361627,
         -0.6232746 ,  0.14534411, -0.18167171,  0.6569123 ,  0.1839671 ,
         -0.22669941],
        [ 0.05784675, -0.08639347,  0.15565763,  0.15329911,  0.3633938 ,
          0.30996713, -0.65654176, -0.27610075,  0.10455072,  0.39144558,
          0.45619318],
        [ 0.53984165,  0.33030233,  0.00461571, -0.31999126, -0.12518352,
          0.0200702 ,  0.58906126, -0.66869694, -0.25228974,  0.38089374,
          0.36678168],
        [ 0.04081254, -0.6839111 ,  0.19825251,  0.6161713 ,  0.34876764,
          0.08331899,  1.1461693 ,  0.44465235, -1.2369689 ,  0.27049637,
          0.07664751]], dtype=float32),
 array([ 0.2718082 , -0.10040622, -0.11132529,  0.40349245,  0.19468038,
        -0.06789723,  0.1838816 ,  0.20147079,  0.22537565,  0.39423835,
         0.17517923], dtype=float32)]

In [54]:
y_log=model.predict(X_test_scaled)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 503us/step

In [55]:
import numpy as np
y_pred=np.where(y_log>0.5,1,0)

In [56]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8625